---
- name: cherry-pick fixes to haproxy_server
  command: "git cherry-pick {{ item }}"
  args:
    chdir: /etc/ansible/roles/haproxy_server
  with_items:
    - b7834dd051cff7d6c26a2f92159099d743256836 # Add support for extra VIPs with TLS enabled
    - 693cdb1afc65bd30375cb08a10c5aaabec9a366d # Align the usage of the two extra lb vip parameters
    - 049b479b65a700815bd4bbec165e72e33a8fe627 # Add options to override which addresses haproxy binds to
    - f35867466c02fccbf009ea103580c120b225e371 # Add extra controls for frontend redirects
    - 04932a7c74b5cb8e7247019b141e3ddeddb072be # Allow extra parameters to be passed to certbot
    - ba3a89944bee0d76753e55f029e53aaf685f7541 # Allow multiple methods of installing certbot
    - 1d386a57f527bde36153e5606c3c8189899007ae # Add option to use distro provided certbot package
    - a254facacf3706a83385e42ac0d76f859c9355bd # Install self-signed certificate before certbot has run for the first time
    - 28eb2c1d1dbb3963c17c24d8ac5d43c6b0fcdc6e # Add documentation for HA HAProxy with LetsEncrypt certificates
    - dbc8fe1fe2ec675655624ec7ee3996b20ee6e7a4 # Use a certbot pre-hook to ensure haproxy backend is up before renewal
    - 449aa69edc835c722bf6f304a0bd581f9388fe88 # Allow frontend acl to be undefined.
    - 5fba658296634c9f32581c965c8510ff6cdf2b90 # Ensure there is no race between haproxy and certbot for initial cert
    - 0343893881dce50bf9786265e4b2ea77972114b6 # Define http-01 params with already provided variables
  become: true

- name: cherry-pick fixes to lxc_container_create
  command: "git cherry-pick {{ item }}"
  args:
    chdir: /etc/ansible/roles/lxc_container_create
  with_items:
    - fd62da8df031b07706ea0f5b045f7f3d03519e3f # Allow user to override UseRoutes in template
    - 8b3ff31c3a70e48239e7d5f349d7bab93779e9bc # Allow user to override UseDNS in template
  become: true

- name: cherry-pick fixes to os_cinder
  command: "git cherry-pick {{ item }}"
  args:
    chdir: /etc/ansible/roles/os_cinder
  with_items:
    - "f5ba9b5b9a88ab09f3d6afded011976525c863a3" # Set correct permissions for rootwrap.d
  become: true

- name: cherry-pick fixes to os_nova
  command: "git cherry-pick {{ item }}"
  args:
    chdir: /etc/ansible/roles/os_nova
  with_items:
    - "1958a954b989e391567be4632d794c22ce03bff6" # Simplify scheduler filter additions
  become: true

- name: cherry-pick fixes to os_neutron
  shell: "{{ item }}"
  environment: "{{ proxy_env }}"
  args:
    chdir: /etc/ansible/roles/os_neutron
  with_items:
    - "git fetch https://review.opendev.org/openstack/openstack-ansible-os_neutron refs/changes/22/768522/1 && git cherry-pick FETCH_HEAD" # Allow overriding firewall_driver for ovs
  become: true

- name: cherry-pick fixes to openstack-ansible
  command: "git cherry-pick {{ item }}"
  args:
    chdir: /opt/openstack-ansible
  with_items:
    - 9d7969f5880b5cd69c7a22e549d9e7f71843cf2c # Add documentation for deploying letsencrypt certificates
    - 9c0303398182361752d48193f4e7a38597647b18 # Remove git repo haproxy backend
    - a0761a0e66aebad2951473e676c603cca59fe567 # Simplify path for letsencrypt usage

- name: apply patches to run-upgrade.sh for ceph upgrades
  shell: "git stash && git fetch https://review.opendev.org/openstack/openstack-ansible refs/changes/78/710778/6 && git cherry-pick FETCH_HEAD && git stash pop"
  environment: "{{ proxy_env }}"
  args:
    chdir: "/opt/openstack-ansible"

- name: avoid tempest like the plague
  replace:
    path: "/opt/openstack-ansible/playbooks/setup-openstack.yml"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp:  "^- (.*): os-tempest-install.yml$"
      replace: "#- \\1: os-tempest-install.yml"
    - regexp:  "^  when: \\(tempest_install(.*)$"
      replace: "#  when: (tempest_install\\1"

# vim: nowrap
