- name: Configure the host running openstack-ansible
  hosts:
    - openstack_ansible

  tasks:
    - name: generate deployment key
      openssh_keypair:
        type: ed25519
        path: /root/.ssh/id_ed25519
      become: true
      register: _id_keypair

    - name: propagate deployment key
      authorized_key:
        user: root
        key: "{{ _id_keypair.public_key }} {{ inventory_hostname }}"
      become: true
      delegate_to: "{{ item }}"
      with_items: "{{ groups['openstack'] }}"
